In [1]:
import torch
from Time2Vec.periodic_activations import SineActivation, CosineActivation
import torch.nn as nn
import numpy as np

In [3]:
l1 = SineActivation(1, 50)

In [29]:
a = torch.randint(1, 10, (2, 2, 1), dtype=torch.float32)

In [21]:
class Time2vec(nn.Module):
    def __init__(self, c_in, c_out, activation="cos"):
        super().__init__()
        self.wnbn = nn.Linear(c_in, c_out - 1, bias=True)
        self.w0b0 = nn.Linear(c_in, 1, bias=True)
        self.act = torch.cos if activation == "cos" else torch.sin

    def forward(self, x):
        part0 = self.act(self.w0b0(x))
        # print(part0.shape)
        part1 = self.act(self.wnbn(x))
        # print(part1.shape)
        return torch.cat([part0, part1], -1)

In [24]:
l1 = Time2vec(1, 50)

tensor([[[5., 5., 8., 6., 4., 8., 7., 1., 3., 9., 8., 2., 4., 7., 1., 1., 9.,
          1., 3., 1., 3., 5., 8., 7., 9., 1., 7., 8., 5., 8., 3., 1., 4., 4.,
          4., 7., 1., 9., 7., 3., 5., 4., 8., 2., 9., 8., 9., 9., 9., 5.]],

        [[6., 2., 1., 5., 2., 8., 3., 8., 9., 4., 2., 7., 7., 5., 1., 8., 4.,
          9., 6., 4., 7., 6., 6., 7., 7., 6., 2., 9., 4., 8., 1., 9., 7., 5.,
          7., 2., 2., 8., 9., 2., 9., 6., 8., 5., 2., 3., 2., 7., 7., 6.]]])

In [31]:
l1(a)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x50 and 1x1)

In [32]:
x = [1,2,3]
x + 4

TypeError: can only concatenate list (not "int") to list

In [4]:
a = torch.tensor([[1, 2],
                  [2, 1]])
a.shape

torch.Size([2, 2])

In [6]:
b =  torch.tensor([[[1, 2], [2, 1]],
                   [[1, 2], [2, 1]]])
b.shape

torch.Size([2, 2, 2])

In [14]:
a.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [15]:
(a + b).shape, a+b

(torch.Size([2, 2, 2]),
 tensor([[[2, 4],
          [4, 2]],
 
         [[2, 4],
          [4, 2]]]))

In [2]:
import torch
import random

# Set the random seed for reproducibility (optional)
random.seed(42)

# Create a torch.tensor of size (3, 4) with random values between 0 and 1
a = torch.randint(0, 10, (2, 2, 3, 4), dtype=torch.int32)
b = a[:, -1, :]
a, b, b.shape

(tensor([[[[1, 6, 3, 8],
           [1, 9, 4, 1],
           [0, 3, 3, 0]],
 
          [[9, 6, 1, 2],
           [2, 8, 7, 3],
           [1, 6, 7, 4]]],
 
 
         [[[8, 1, 0, 6],
           [5, 2, 4, 7],
           [9, 6, 5, 4]],
 
          [[8, 6, 1, 4],
           [9, 2, 4, 0],
           [1, 0, 3, 0]]]], dtype=torch.int32),
 tensor([[[9, 6, 1, 2],
          [2, 8, 7, 3],
          [1, 6, 7, 4]],
 
         [[8, 6, 1, 4],
          [9, 2, 4, 0],
          [1, 0, 3, 0]]], dtype=torch.int32),
 torch.Size([2, 3, 4]))

In [4]:
a = torch.randint(0, 10, (2, 1), dtype=torch.int32)
b = torch.randint(0, 10, (2, 2), dtype=torch.int32)

In [5]:
a, b

(tensor([[6],
         [8]], dtype=torch.int32),
 tensor([[0, 9],
         [8, 2]], dtype=torch.int32))

In [6]:
a + b

tensor([[ 6, 15],
        [16, 10]], dtype=torch.int32)

In [33]:
a = torch.randint(0, 10, (2, 4), dtype=torch.int32)
b = torch.randint(0, 10, (2, 3, 4), dtype=torch.int32)
a, b

(tensor([[9, 7, 1, 5],
         [7, 3, 7, 0]], dtype=torch.int32),
 tensor([[[4, 3, 1, 6],
          [6, 9, 7, 1],
          [2, 2, 4, 8]],
 
         [[7, 9, 1, 7],
          [2, 8, 0, 2],
          [4, 6, 4, 8]]], dtype=torch.int32))

In [33]:
a = torch.randint(0,1, (1, 1, 10), dtype=torch.int32)
periods = torch.tensor([0.25, 0.5, 0.75, 1, 2, 4, 8, 16, 24, 7*24, 28*24, 365*24]*3600, dtype=torch.float32)

In [34]:
a/periods

RuntimeError: The size of tensor a (10) must match the size of tensor b (43200) at non-singleton dimension 2

In [34]:
a.unsqueeze(-2)

tensor([[[9, 7, 1, 5]],

        [[7, 3, 7, 0]]], dtype=torch.int32)

In [39]:
pos_logits = (a.unsqueeze(-2) * b)

In [40]:
pos_logits

tensor([[[36, 21,  1, 30],
         [54, 63,  7,  5],
         [18, 14,  4, 40]],

        [[49, 27,  7,  0],
         [14, 24,  0,  0],
         [28, 18, 28,  0]]], dtype=torch.int32)

In [45]:
import torch
import numpy as np

class Time2Vec_abs(torch.nn.Module):
    def __init__(self):
        super(Time2Vec_abs, self).__init__()
        self.P = 12
        self.periods = torch.tensor([0.25*3600, 0.5*3600, 0.75*3600, 1*3600, 2*3600, 4*3600, 8*3600, 16*3600, 24*3600
                                        , 7*24*3600, 28*24*3600, 365*24*3600], dtype=torch.float32)
        self.phase_sin = torch.nn.Parameter(torch.randn(self.P), requires_grad=True)
        self.phase_cos = torch.nn.Parameter(torch.randn(self.P), requires_grad=True)

    def forward(self, time_seq):
        # relative time features
        batch_size= time_seq.shape[0]
        seq_len = time_seq.shape[1]
        time_seq = time_seq.unsqueeze(-1)
        periods_exp = self.periods.unsqueeze(0).unsqueeze(0)
        time_scaled = time_seq / periods_exp  # divide by the periods
        features_cos = torch.cos((2* np.pi * time_scaled) + self.phase_cos)
        features_sin = torch.sin((2* np.pi * time_scaled) + self.phase_sin)
        features_log = torch.log(time_seq)

        stacked_features = torch.stack((features_cos, features_sin), dim=-1)
        stacked_features = stacked_features.view(batch_size, seq_len,-1)
        features_log = features_log
        concat_features = torch.cat([stacked_features, features_log], dim=-1)
        return concat_features


t2v = Time2Vec_abs()
a = t2v(data)

In [8]:
a.shape

In [5]:
data = torch.randint(0, 1000000, (2, 3, 3), dtype=torch.int32)


In [7]:
data

tensor([[[358095, 620121, 290337],
         [ 86281, 661793,  70281],
         [678833, 153314, 619700]],

        [[207788, 696571, 503367],
         [747926, 907336, 741619],
         [940001,  13087, 195393]]], dtype=torch.int32)

In [8]:
data[..., 1]

tensor([[620121, 661793, 153314],
        [696571, 907336,  13087]], dtype=torch.int32)

In [5]:
a.shape, b.shape, c.shape, d.shape, e.shape

(torch.Size([2, 3, 12]),
 torch.Size([2, 3, 12]),
 torch.Size([2, 3, 24]),
 torch.Size([2, 3, 1]),
 torch.Size([2, 3, 25]))

In [6]:
a[0,0], b[0,0], c[0,0], d[0,0], e[0,0]

(tensor([ 0.8586,  0.4725,  0.7051,  0.6866,  0.7811, -0.1613,  0.1674, -0.3789,
         -0.3511,  0.9992,  0.7286,  0.9522], grad_fn=<SelectBackward0>),
 tensor([-0.2799,  0.4996, -0.2968, -0.8747, -0.8488,  0.3596,  0.1649,  0.8939,
         -0.6596, -0.4216, -0.4306,  0.9997], grad_fn=<SelectBackward0>),
 tensor([ 0.8586, -0.2799,  0.4725,  0.4996,  0.7051, -0.2968,  0.6866, -0.8747,
          0.7811, -0.8488, -0.1613,  0.3596,  0.1674,  0.1649, -0.3789,  0.8939,
         -0.3511, -0.6596,  0.9992, -0.4216,  0.7286, -0.4306,  0.9522,  0.9997],
        grad_fn=<SelectBackward0>),
 tensor([2.0794]),
 tensor([ 0.8586, -0.2799,  0.4725,  0.4996,  0.7051, -0.2968,  0.6866, -0.8747,
          0.7811, -0.8488, -0.1613,  0.3596,  0.1674,  0.1649, -0.3789,  0.8939,
         -0.3511, -0.6596,  0.9992, -0.4216,  0.7286, -0.4306,  0.9522,  0.9997,
          2.0794], grad_fn=<SelectBackward0>))

In [13]:
import torch
import numpy as np

class Time2Vec_rel(torch.nn.Module):
    def __init__(self):
        super(Time2Vec_rel, self).__init__()
        self.P = 32
        self.periods = torch.logspace(np.log10(1), np.log10(4*7*24*3600), self.P)
        self.phase_sin = torch.nn.Parameter(torch.randn(self.P), requires_grad=True)
        self.phase_cos = torch.nn.Parameter(torch.randn(self.P), requires_grad=True)

    def forward(self, time_seq):
        # relative time features
        batch_size= time_seq.shape[0]
        seq_len = time_seq.shape[1]
        time_seq = time_seq.unsqueeze(-1)
        periods_exp = self.periods.unsqueeze(0).unsqueeze(0)
        time_scaled = time_seq / periods_exp  # divide by the periods
        features_cos = torch.cos((2* np.pi * time_scaled) + self.phase_cos)
        features_sin = torch.sin((2* np.pi * time_scaled) + self.phase_sin)
        features_log = torch.log(time_seq)
        stacked_features = torch.stack((features_cos, features_sin), dim=-1)
        stacked_features = stacked_features.view(batch_size, seq_len,-1)
        features_log = features_log
        concat_features = torch.cat([stacked_features, features_log], dim=-1)
        return concat_features

t2v_rel = Time2Vec_rel()
a, b, c, d, e = t2v_rel(data)

torch.Size([2, 3, 32])
torch.Size([2, 3, 32])
torch.Size([2, 3, 32])


In [15]:
a[0,0], b[0,0], c[0,0], d[0,0], e[0,0]

(tensor([ 0.9812,  0.7213,  0.9280,  0.8491, -0.5070, -0.2947, -0.9098,  0.5542,
          0.4496,  0.9972,  0.2903,  0.5482,  0.7048,  0.8395,  0.7438,  0.9027,
          0.8852,  0.5587,  0.9885,  0.9711,  0.4583,  0.0995,  0.3147,  0.5652,
          0.6809,  0.9035,  0.4413,  0.9594,  0.6966,  0.9997,  0.9883,  0.9958],
        grad_fn=<SelectBackward0>),
 tensor([-0.1743, -0.9322,  0.3337,  0.6507,  0.3062, -0.6344,  0.8506,  0.5733,
          0.9571,  0.4531,  0.9584,  0.8163, -0.3037, -0.9887,  0.3409,  0.6202,
         -0.9908, -0.9766,  0.6305,  0.3558,  0.2376, -0.0075, -0.9236, -0.4971,
          1.0000, -0.7613, -0.9252,  0.7560, -0.5194, -0.9500, -0.6805,  0.6033],
        grad_fn=<SelectBackward0>),
 tensor([ 0.9812, -0.1743,  0.7213, -0.9322,  0.9280,  0.3337,  0.8491,  0.6507,
         -0.5070,  0.3062, -0.2947, -0.6344, -0.9098,  0.8506,  0.5542,  0.5733,
          0.4496,  0.9571,  0.9972,  0.4531,  0.2903,  0.9584,  0.5482,  0.8163,
          0.7048, -0.3037,  0.8395,

In [14]:
a.shape, b.shape, c.shape, d.shape, e.shape

(torch.Size([2, 3, 32]),
 torch.Size([2, 3, 32]),
 torch.Size([2, 3, 64]),
 torch.Size([2, 3, 1]),
 torch.Size([2, 3, 65]))

In [11]:
torch.tensor([0.25, 0.5, 0.75, 1, 2, 4, 8, 16, 24, 7*24, 28*24, 365*24]) * 3600

tensor([9.0000e+02, 1.8000e+03, 2.7000e+03, 3.6000e+03, 7.2000e+03, 1.4400e+04,
        2.8800e+04, 5.7600e+04, 8.6400e+04, 6.0480e+05, 2.4192e+06, 3.1536e+07])

In [65]:
class Time2Vec_abs(torch.nn.Module):
    def __init__(self, periods):
        super(Time2Vec_abs, self).__init__()
        self.P = periods
        self.periods = torch.tensor(
            [0.25 * 3600, 0.5 * 3600, 0.75 * 3600, 1 * 3600, 2 * 3600, 4 * 3600, 8 * 3600, 16 * 3600, 24 * 3600
                , 7 * 24 * 3600, 28 * 24 * 3600, 365 * 24 * 3600], dtype=torch.float32)
        self.phase_sin = torch.nn.Parameter(torch.randn(self.P), requires_grad=True)
        self.phase_cos = torch.nn.Parameter(torch.randn(self.P), requires_grad=True)

    def forward(self, time_seq):
        # relative time features
        batch_size = time_seq.shape[0]
        seq_len = time_seq.shape[1]
        time_seq = time_seq.unsqueeze(-1)
        periods_exp = self.periods.unsqueeze(0).unsqueeze(0)
        periods_exp = periods_exp
        time_scaled = time_seq / periods_exp  # divide by the periods
        features_cos = torch.cos((2 * np.pi * time_scaled) + self.phase_cos)
        features_sin = torch.sin((2 * np.pi * time_scaled) + self.phase_sin)
        features_log = torch.log(time_seq)
        stacked_features = torch.stack((features_cos, features_sin), dim=-1)
        stacked_features = stacked_features.view(batch_size, seq_len, -1)
        features_log = features_log
        concat_features = torch.cat([stacked_features, features_log], dim=-1)
        return concat_features


In [66]:
t2v_abs = Time2Vec_abs(12)

In [67]:
r = t2v_abs(data)

In [69]:
data

tensor([[324124, 625816, 501223],
        [ 29305, 374396, 161464]], dtype=torch.int32)

In [68]:
r

tensor([[[ 8.1646e-01,  3.7902e-01,  4.6314e-01, -3.1135e-01, -2.9784e-01,
           6.3701e-01,  6.3793e-01, -4.3623e-01,  4.4739e-01,  3.1015e-01,
          -7.8072e-01,  4.0006e-01,  3.4092e-01,  8.2771e-01, -9.9757e-01,
          -8.2925e-01, -1.3332e-01, -5.7070e-01, -8.7598e-01, -3.2508e-01,
          -2.0294e-01,  6.0557e-01,  9.5560e-01, -7.8371e-01,  1.2689e+01],
         [-3.7551e-01,  9.8748e-01,  1.8769e-01, -3.4628e-01, -9.2892e-01,
          -8.1749e-01,  9.3707e-01, -9.9325e-01, -1.5336e-01, -2.9793e-01,
          -5.5378e-01,  6.5977e-01, -4.8149e-01, -9.0419e-01, -7.5599e-03,
          -6.2120e-01,  1.8415e-01,  6.1221e-01,  8.7950e-01,  3.1812e-01,
          -8.3488e-01,  9.9066e-01,  9.3617e-01, -7.4498e-01,  1.3347e+01],
         [ 7.0532e-01, -8.4934e-01, -9.2585e-01,  8.5124e-01, -2.7345e-01,
          -9.5511e-01, -5.0391e-01,  6.9508e-01, -8.7902e-01, -7.9881e-01,
          -3.6162e-01, -9.9432e-01, -5.5635e-01,  3.7117e-02, -8.5842e-01,
          -9.9231e-01, 

In [9]:
import numpy as np

class TimeEncoder_abs(torch.nn.Module):
    def __init__(self):
        super(TimeEncoder_abs, self).__init__()
        # Set the periods for absolute and relative time
        self.P_abs = 12
        # The vector phi is a learned parameter
        self.phi = nn.Parameter(torch.Tensor(2 * self.P_abs))
        # Manually chosen periods of real-life importance
        self.abs_periods = (torch.tensor([0.25, 0.5, 0.75, 1, 2, 4, 8, 16, 24, 168, 672, 8760],
                                         dtype=torch.float32) * 3600)
        # Log scale periods for relative time difference

    def forward(self, t):
        # Calculate the features for absolute and relative time
        r_abs = self.encode_time(t, self.P_abs, self.abs_periods)
        return r_abs

    def encode_time(self, t, P, periods):
        t = t.float()
        periods = periods.unsqueeze(0).unsqueeze(0)
        features = []
        for i in range(1, P + 1):
            pi = periods[..., i - 1]
            phi_2i_minus_1 = self.phi[2 * i - 2]
            phi_2i = self.phi[2 * i - 1]
            features.append(torch.cos(2 * np.pi * t / pi + phi_2i_minus_1))
            features.append(torch.sin(2 * np.pi * t / pi + phi_2i))

        features.append(torch.log(t))
        return torch.cat(features, dim=-1)

In [35]:
time_seqs = torch.randint(0, 1000000, (128, 200, 2), dtype=torch.int32)

In [36]:
time_seqs.shape

torch.Size([128, 200, 2])

In [38]:
time_seqs[..., 0].shape

torch.Size([128, 200])

In [40]:
time_seqs[..., 1].shape

IndexError: index 2 is out of bounds for dimension 1 with size 2

In [23]:
time_seqs.unsqueeze(-1).shape

torch.Size([128, 200, 1])

In [17]:
t2v = TimeEncoder_abs()

In [24]:
t_emb = t2v(time_seqs.unsqueeze(-1))

In [26]:
t_emb

tensor([[[ 8.6956e-01, -4.9383e-01, -9.6684e-01,  ...,  9.9820e-01,
          -5.9184e-01,  1.2616e+01],
         [ 9.7352e-01,  2.2858e-01, -9.9336e-01,  ...,  9.8412e-01,
          -5.9184e-01,  1.3705e+01],
         [ 3.0229e-01,  9.5322e-01,  8.0694e-01,  ...,  9.9956e-01,
          -5.9184e-01,  1.1916e+01],
         ...,
         [-9.9961e-01,  2.7928e-02, -1.3965e-02,  ...,  9.9989e-01,
          -5.9184e-01,  1.1227e+01],
         [ 6.4283e-01, -7.6601e-01,  9.0632e-01,  ...,  9.9904e-01,
          -5.9184e-01,  1.2299e+01],
         [ 4.0026e-01, -9.1640e-01, -8.3674e-01,  ...,  9.9696e-01,
          -5.9184e-01,  1.2877e+01]],

        [[ 4.2601e-01, -9.0472e-01,  8.4440e-01,  ...,  9.9787e-01,
          -5.9184e-01,  1.2699e+01],
         [ 7.4777e-01,  6.6396e-01,  9.3482e-01,  ...,  9.8434e-01,
          -5.9184e-01,  1.3698e+01],
         [-2.7960e-02, -9.9961e-01,  6.9715e-01,  ...,  9.8547e-01,
          -5.9184e-01,  1.3661e+01],
         ...,
         [-4.9380e-01, -8

In [25]:
t_emb.shape

torch.Size([128, 200, 25])

In [10]:
l1 = [(1,2), (2,3)]

In [15]:
list(zip([1,2], [10,1]))

[(1, 10), (2, 1)]

In [16]:
def time_feature_creation_rel(User):
    # relative time feature
    print("Time feature deriving: Rel")
    for user in User:
        items = list(map(lambda x: x[0], User[user]))
        timestamps = list(map(lambda x: x[1], User[user]))
        time_gaps = [timestamps[i+1] - timestamps[i] for i in range(len(timestamps) - 1)]
        time_gaps.append(0)
        User[user] = list(zip(items, time_gaps))
    print("feature Done")

In [18]:
User = dict()
User[0] = [(1,1), [2,11], [3, 21]]

In [19]:
time_feature_creation_rel(User)


Time feature deriving: Rel
feature Done


In [20]:
User

{0: [(1, 10), (2, 10), (3, 0)]}

In [55]:
x = torch.logspace(np.log10(1), np.log10(4 * 7 * 24 * 3600), 32).float()

In [56]:
x[-1]

tensor(2419200.)

In [54]:
torch.tensor(8760 * 3600).float()

tensor(31536000.)

In [30]:
list(zip([0,1], [(1,2), [3,4]]))

[(0, (1, 2)), (1, (3, 4))]

In [32]:
x = (1,2,3,4)
type(x)

tuple